/* Layout verification for a hand-declared ABI.
 *
 * The failure this exists to prevent: a struct field at the wrong offset does
 * not crash, it reads its neighbour. The symptom appears far from the cause —
 * a drifting pose, a swapchain index off the end — and from outside the guest
 * it is nearly undebuggable.
 *
 * So nothing here is trusted on the strength of having been written carefully.
 * Where ground truth is available it is asserted against; where it is not, the
 * build says so out loud instead of implying verification that did not happen. */
#ifndef KL_VRAPI_ABI_H
#define KL_VRAPI_ABI_H

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

/* Generated by tools/metavision-vrapi-abi from a real libvrapi.so.
 * Absent by default: it is derived from a file we cannot redistribute. */
#if defined(KL_VRAPI_HAVE_ABI_EXPECT)
#  include "vrapi_abi_expect.h"
#  define KL_ABI_VERIFIED 1
#else
#  define KL_ABI_VERIFIED 0
#endif

/* Assert against ground truth when we have it.
 *
 * The expected values are spelled the way the generator spells them, so a
 * check whose macro the generator never emitted stays inert rather than
 * silently comparing against nothing. */
#define KL_ABI_EXPECT_OFFSET(type, field) KL_ABI_OFFSET_##type##_##field
#define KL_ABI_EXPECT_SIZE(type)          KL_ABI_SIZEOF_##type

#if KL_ABI_VERIFIED
#  define KL_ABI_CHECK_OFFSET(type, field) \
      _Static_assert(offsetof(type, field) == KL_ABI_EXPECT_OFFSET(type, field), \
                     "ABI drift: " #type "." #field " is not where the real " \
                     "library puts it; regenerate or fix the declaration")
#  define KL_ABI_CHECK_SIZE(type) \
      _Static_assert(sizeof(type) == KL_ABI_EXPECT_SIZE(type), \
                     "ABI drift: sizeof(" #type ") disagrees with the real header")
#else
/* Unverified: keep the reference so the field name still has to exist and the
 * check compiles, but assert nothing we have not actually measured. */
#  define KL_ABI_CHECK_OFFSET(type, field) \
      _Static_assert(offsetof(type, field) < sizeof(type), \
                     "declared but unverified: " #type "." #field)
#  define KL_ABI_CHECK_SIZE(type) \
      _Static_assert(sizeof(type) > 0, "declared but unverified: " #type)
#endif

/* Abort naming what went wrong. A title that trips one of these produces a line
 * that is the whole bug report; anything quieter costs hours. */
#define KL_VRAPI_FATAL(fmt, ...) \
    do { \
        fprintf(stderr, "[klepton/vrapi] FATAL %s: " fmt "\n", __func__, ##__VA_ARGS__); \
        fflush(stderr); \
        abort(); \
    } while (0)

#define KL_VRAPI_UNIMPLEMENTED() \
    KL_VRAPI_FATAL("not implemented — a title reached this, so it needs writing")

/* Validate a structure tag before reading anything else out of a struct. This
 * is the cheap check that turns a layout error into a located error. */
#define KL_VRAPI_EXPECT_TYPE(actual, wanted) \
    do { \
        if ((int)(actual) != (int)(wanted)) \
            KL_VRAPI_FATAL("structure tag %d, expected %d (%s) — " \
                           "layout mismatch, not a guest bug", \
                           (int)(actual), (int)(wanted), #wanted); \
    } while (0)

/* One line at startup, so a log always records whether the ABI was checked
 * against a real binary or merely declared. */
static inline void kl_vrapi_abi_banner(void)
{
    fprintf(stderr, "[klepton/vrapi] ABI %s\n",
            KL_ABI_VERIFIED
              ? "verified against libvrapi.so"
              : "DECLARED, NOT VERIFIED — run tools/metavision-vrapi-abi "
                "against a real libvrapi.so before trusting struct layouts");
}

#endif
