/* GENERATED by tools/metavision-vrapi-abi --dwarf. Do not edit.
 * Ground truth read from the DWARF in libvrapi.so —
 * the exact build the guest was compiled against.
 * Present means kl_vrapi.h's declarations are checked at compile time. */
#ifndef KL_VRAPI_ABI_EXPECT_H
#define KL_VRAPI_ABI_EXPECT_H

#define KL_ABI_SIZEOF_ovrLayerHeader2 40
#define KL_ABI_SIZEOF_ovrModeParms 56
#define KL_ABI_SIZEOF_ovrPosef 28
#define KL_ABI_SIZEOF_ovrRigidBodyPosef 96
#define KL_ABI_SIZEOF_ovrSubmitFrameDescription2 48
#define KL_ABI_SIZEOF_ovrTracking2 360

#define KL_ABI_OFFSET_ovrLayerHeader2_Type 0
#define KL_ABI_OFFSET_ovrLayerHeader2_Flags 4
#define KL_ABI_OFFSET_ovrLayerHeader2_ColorScale 8
#define KL_ABI_OFFSET_ovrLayerHeader2_SrcBlend 24
#define KL_ABI_OFFSET_ovrLayerHeader2_DstBlend 28
#define KL_ABI_OFFSET_ovrModeParms_Type 0
#define KL_ABI_OFFSET_ovrModeParms_Flags 4
#define KL_ABI_OFFSET_ovrModeParms_Java 8
#define KL_ABI_OFFSET_ovrModeParms_Display 32
#define KL_ABI_OFFSET_ovrModeParms_WindowSurface 40
#define KL_ABI_OFFSET_ovrModeParms_ShareContext 48
#define KL_ABI_OFFSET_ovrPosef_Orientation 0
#define KL_ABI_OFFSET_ovrRigidBodyPosef_Pose 0
#define KL_ABI_OFFSET_ovrRigidBodyPosef_AngularVelocity 28
#define KL_ABI_OFFSET_ovrRigidBodyPosef_LinearVelocity 40
#define KL_ABI_OFFSET_ovrRigidBodyPosef_AngularAcceleration 52
#define KL_ABI_OFFSET_ovrRigidBodyPosef_LinearAcceleration 64
#define KL_ABI_OFFSET_ovrRigidBodyPosef_dead0 76
#define KL_ABI_OFFSET_ovrRigidBodyPosef_TimeInSeconds 80
#define KL_ABI_OFFSET_ovrRigidBodyPosef_PredictionInSeconds 88
#define KL_ABI_OFFSET_ovrSubmitFrameDescription2_Flags 0
#define KL_ABI_OFFSET_ovrSubmitFrameDescription2_SwapInterval 4
#define KL_ABI_OFFSET_ovrSubmitFrameDescription2_FrameIndex 8
#define KL_ABI_OFFSET_ovrSubmitFrameDescription2_DisplayTime 16
#define KL_ABI_OFFSET_ovrSubmitFrameDescription2_LayerCount 32
#define KL_ABI_OFFSET_ovrSubmitFrameDescription2_Layers 40
#define KL_ABI_OFFSET_ovrTracking2_Status 0
#define KL_ABI_OFFSET_ovrTracking2_dead1 4
#define KL_ABI_OFFSET_ovrTracking2_HeadPose 8
#define KL_ABI_OFFSET_ovrTracking2_Eye 104

#endif
